// Auto-generated by bin/stimulus-imports — DO NOT EDIT MANUALLY.
import ButtonController from "../controllers/decor/daisy/button_controller";
import DaisyClickToCopyController from "../controllers/decor/daisy/click_to_copy_controller";
import CodeBlockController from "../controllers/decor/daisy/code_block_controller";
import DaisyDropdownController from "../controllers/decor/daisy/dropdown_controller";
import DaisyFlashController from "../controllers/decor/daisy/flash_controller";
import DateCalendarController from "../controllers/decor/daisy/forms/date_calendar_controller";
import SwitchController from "../controllers/decor/daisy/forms/switch_controller";
import DaisyMapController from "../controllers/decor/daisy/map_controller";
import ConfirmModalController from "../controllers/decor/daisy/modals/confirm_modal_controller";
import ModalCloseButtonController from "../controllers/decor/daisy/modals/modal_close_button_controller";
import ModalController from "../controllers/decor/daisy/modals/modal_controller";
import ModalOpenButtonController from "../controllers/decor/daisy/modals/modal_open_button_controller";
import NotificationManagerController from "../controllers/decor/daisy/notification_manager_controller";
import DaisyProgressController from "../controllers/decor/daisy/progress_controller";
import TabsController from "../controllers/decor/daisy/tabs_controller";
import ProgressAnimationController from "../controllers/decor/progress_animation_controller";
import CarouselController from "../controllers/decor/suite/carousel_controller";
import SuiteClickToCopyController from "../controllers/decor/suite/click_to_copy_controller";
import SuiteDropdownController from "../controllers/decor/suite/dropdown_controller";
import SuiteFlashController from "../controllers/decor/suite/flash_controller";
import SuiteMapController from "../controllers/decor/suite/map_controller";
import SuiteProgressController from "../controllers/decor/suite/progress_controller";
import TooltipController from "../controllers/decor/suite/tooltip_controller";

export const CONTROLLERS = {
  "decor--daisy--button": ButtonController,
  "decor--daisy--click-to-copy": DaisyClickToCopyController,
  "decor--daisy--code-block": CodeBlockController,
  "decor--daisy--dropdown": DaisyDropdownController,
  "decor--daisy--flash": DaisyFlashController,
  "decor--daisy--forms--date-calendar": DateCalendarController,
  "decor--daisy--forms--switch": SwitchController,
  "decor--daisy--map": DaisyMapController,
  "decor--daisy--modals--confirm-modal": ConfirmModalController,
  "decor--daisy--modals--modal-close-button": ModalCloseButtonController,
  "decor--daisy--modals--modal": ModalController,
  "decor--daisy--modals--modal-open-button": ModalOpenButtonController,
  "decor--daisy--notification-manager": NotificationManagerController,
  "decor--daisy--progress": DaisyProgressController,
  "decor--daisy--tabs": TabsController,
  "decor--progress-animation": ProgressAnimationController,
  "decor--suite--carousel": CarouselController,
  "decor--suite--click-to-copy": SuiteClickToCopyController,
  "decor--suite--dropdown": SuiteDropdownController,
  "decor--suite--flash": SuiteFlashController,
  "decor--suite--map": SuiteMapController,
  "decor--suite--progress": SuiteProgressController,
  "decor--suite--tooltip": TooltipController,
};
