// Auto-generated by bin/stimulus-imports — DO NOT EDIT MANUALLY.
import DaisyAiChatWidgetController from "../controllers/decor/daisy/ai_chat/widget_controller";
import DaisyButtonController from "../controllers/decor/daisy/button_controller";
import DaisyClickToCopyController from "../controllers/decor/daisy/click_to_copy_controller";
import DaisyCodeBlockController from "../controllers/decor/daisy/code_block_controller";
import DaisyDropdownController from "../controllers/decor/daisy/dropdown_controller";
import DaisyFlashController from "../controllers/decor/daisy/flash_controller";
import DaisyFormsButtonRadioGroupController from "../controllers/decor/daisy/forms/button_radio_group_controller";
import DaisyFormsCheckboxController from "../controllers/decor/daisy/forms/checkbox_controller";
import DaisyFormsDateCalendarController from "../controllers/decor/daisy/forms/date_calendar_controller";
import DaisyFormsExpandingCheckboxCollectionController from "../controllers/decor/daisy/forms/expanding_checkbox_collection_controller";
import DaisyFormsFileUploadController from "../controllers/decor/daisy/forms/file_upload_controller";
import DaisyFormsMultiImageUploadController from "../controllers/decor/daisy/forms/multi_image_upload_controller";
import DaisyFormsNumberFieldController from "../controllers/decor/daisy/forms/number_field_controller";
import DaisyFormsRadioController from "../controllers/decor/daisy/forms/radio_controller";
import DaisyFormsSearchableMultiSelectController from "../controllers/decor/daisy/forms/searchable_multi_select_controller";
import DaisyFormsSearchableSelectController from "../controllers/decor/daisy/forms/searchable_select_controller";
import DaisyFormsSelectController from "../controllers/decor/daisy/forms/select_controller";
import DaisyFormsSwitchController from "../controllers/decor/daisy/forms/switch_controller";
import DaisyFormsTextAreaController from "../controllers/decor/daisy/forms/text_area_controller";
import DaisyFormsTextFieldController from "../controllers/decor/daisy/forms/text_field_controller";
import DaisyMapController from "../controllers/decor/daisy/map_controller";
import DaisyModalsConfirmController from "../controllers/decor/daisy/modals/confirm_controller";
import DaisyModalsConfirmModalController from "../controllers/decor/daisy/modals/confirm_modal_controller";
import DaisyModalsConfirmTemplateController from "../controllers/decor/daisy/modals/confirm_template_controller";
import DaisyModalsModalCloseButtonController from "../controllers/decor/daisy/modals/modal_close_button_controller";
import DaisyModalsModalController from "../controllers/decor/daisy/modals/modal_controller";
import DaisyModalsModalOpenButtonController from "../controllers/decor/daisy/modals/modal_open_button_controller";
import DaisyModalsModalTriggerController from "../controllers/decor/daisy/modals/modal_trigger_controller";
import SideNavbarController from "../controllers/decor/daisy/nav/side_navbar_controller";
import DaisyNotificationManagerController from "../controllers/decor/daisy/notification_manager_controller";
import DaisyPolygonEditorController from "../controllers/decor/daisy/polygon_editor_controller";
import DaisyProgressController from "../controllers/decor/daisy/progress_controller";
import DaisyTablesBulkActionsBarController from "../controllers/decor/daisy/tables/bulk_actions_bar_controller";
import DaisyTablesTagFilterBarController from "../controllers/decor/daisy/tables/tag_filter_bar_controller";
import DaisyTabsController from "../controllers/decor/daisy/tabs_controller";
import ProgressAnimationController from "../controllers/decor/progress_animation_controller";
import SuiteAiChatWidgetController from "../controllers/decor/suite/ai_chat/widget_controller";
import SuiteButtonController from "../controllers/decor/suite/button_controller";
import CarouselController from "../controllers/decor/suite/carousel_controller";
import SuiteClickToCopyController from "../controllers/decor/suite/click_to_copy_controller";
import SuiteCodeBlockController from "../controllers/decor/suite/code_block_controller";
import SuiteDropdownController from "../controllers/decor/suite/dropdown_controller";
import SuiteFlashController from "../controllers/decor/suite/flash_controller";
import SuiteFormsButtonRadioGroupController from "../controllers/decor/suite/forms/button_radio_group_controller";
import SuiteFormsCheckboxController from "../controllers/decor/suite/forms/checkbox_controller";
import SuiteFormsDateCalendarController from "../controllers/decor/suite/forms/date_calendar_controller";
import SuiteFormsExpandingCheckboxCollectionController from "../controllers/decor/suite/forms/expanding_checkbox_collection_controller";
import SuiteFormsFileUploadController from "../controllers/decor/suite/forms/file_upload_controller";
import FormController from "../controllers/decor/suite/forms/form_controller";
import SuiteFormsMultiImageUploadController from "../controllers/decor/suite/forms/multi_image_upload_controller";
import SuiteFormsNumberFieldController from "../controllers/decor/suite/forms/number_field_controller";
import SuiteFormsRadioController from "../controllers/decor/suite/forms/radio_controller";
import SuiteFormsSearchableMultiSelectController from "../controllers/decor/suite/forms/searchable_multi_select_controller";
import SuiteFormsSearchableSelectController from "../controllers/decor/suite/forms/searchable_select_controller";
import SuiteFormsSelectController from "../controllers/decor/suite/forms/select_controller";
import SuiteFormsSwitchController from "../controllers/decor/suite/forms/switch_controller";
import SuiteFormsTextAreaController from "../controllers/decor/suite/forms/text_area_controller";
import SuiteFormsTextFieldController from "../controllers/decor/suite/forms/text_field_controller";
import SuiteMapController from "../controllers/decor/suite/map_controller";
import SuiteModalsConfirmController from "../controllers/decor/suite/modals/confirm_controller";
import SuiteModalsConfirmModalController from "../controllers/decor/suite/modals/confirm_modal_controller";
import SuiteModalsConfirmTemplateController from "../controllers/decor/suite/modals/confirm_template_controller";
import SuiteModalsModalCloseButtonController from "../controllers/decor/suite/modals/modal_close_button_controller";
import SuiteModalsModalController from "../controllers/decor/suite/modals/modal_controller";
import SuiteModalsModalOpenButtonController from "../controllers/decor/suite/modals/modal_open_button_controller";
import SuiteModalsModalTriggerController from "../controllers/decor/suite/modals/modal_trigger_controller";
import SuiteNotificationManagerController from "../controllers/decor/suite/notification_manager_controller";
import SuitePolygonEditorController from "../controllers/decor/suite/polygon_editor_controller";
import SuiteProgressController from "../controllers/decor/suite/progress_controller";
import SearchAndFilterController from "../controllers/decor/suite/search_and_filter_controller";
import RowController from "../controllers/decor/suite/settings_list/row_controller";
import SuiteTablesBulkActionsBarController from "../controllers/decor/suite/tables/bulk_actions_bar_controller";
import DataTableCellController from "../controllers/decor/suite/tables/data_table_cell_controller";
import DataTableController from "../controllers/decor/suite/tables/data_table_controller";
import SuiteTablesTagFilterBarController from "../controllers/decor/suite/tables/tag_filter_bar_controller";
import SuiteTabsController from "../controllers/decor/suite/tabs_controller";
import TooltipController from "../controllers/decor/suite/tooltip_controller";

export const CONTROLLERS = {
  "decor--daisy--ai-chat--widget": DaisyAiChatWidgetController,
  "decor--daisy--button": DaisyButtonController,
  "decor--daisy--click-to-copy": DaisyClickToCopyController,
  "decor--daisy--code-block": DaisyCodeBlockController,
  "decor--daisy--dropdown": DaisyDropdownController,
  "decor--daisy--flash": DaisyFlashController,
  "decor--daisy--forms--button-radio-group": DaisyFormsButtonRadioGroupController,
  "decor--daisy--forms--checkbox": DaisyFormsCheckboxController,
  "decor--daisy--forms--date-calendar": DaisyFormsDateCalendarController,
  "decor--daisy--forms--expanding-checkbox-collection": DaisyFormsExpandingCheckboxCollectionController,
  "decor--daisy--forms--file-upload": DaisyFormsFileUploadController,
  "decor--daisy--forms--multi-image-upload": DaisyFormsMultiImageUploadController,
  "decor--daisy--forms--number-field": DaisyFormsNumberFieldController,
  "decor--daisy--forms--radio": DaisyFormsRadioController,
  "decor--daisy--forms--searchable-multi-select": DaisyFormsSearchableMultiSelectController,
  "decor--daisy--forms--searchable-select": DaisyFormsSearchableSelectController,
  "decor--daisy--forms--select": DaisyFormsSelectController,
  "decor--daisy--forms--switch": DaisyFormsSwitchController,
  "decor--daisy--forms--text-area": DaisyFormsTextAreaController,
  "decor--daisy--forms--text-field": DaisyFormsTextFieldController,
  "decor--daisy--map": DaisyMapController,
  "decor--daisy--modals--confirm": DaisyModalsConfirmController,
  "decor--daisy--modals--confirm-modal": DaisyModalsConfirmModalController,
  "decor--daisy--modals--confirm-template": DaisyModalsConfirmTemplateController,
  "decor--daisy--modals--modal-close-button": DaisyModalsModalCloseButtonController,
  "decor--daisy--modals--modal": DaisyModalsModalController,
  "decor--daisy--modals--modal-open-button": DaisyModalsModalOpenButtonController,
  "decor--daisy--modals--modal-trigger": DaisyModalsModalTriggerController,
  "decor--daisy--nav--side-navbar": SideNavbarController,
  "decor--daisy--notification-manager": DaisyNotificationManagerController,
  "decor--daisy--polygon-editor": DaisyPolygonEditorController,
  "decor--daisy--progress": DaisyProgressController,
  "decor--daisy--tables--bulk-actions-bar": DaisyTablesBulkActionsBarController,
  "decor--daisy--tables--tag-filter-bar": DaisyTablesTagFilterBarController,
  "decor--daisy--tabs": DaisyTabsController,
  "decor--progress-animation": ProgressAnimationController,
  "decor--suite--ai-chat--widget": SuiteAiChatWidgetController,
  "decor--suite--button": SuiteButtonController,
  "decor--suite--carousel": CarouselController,
  "decor--suite--click-to-copy": SuiteClickToCopyController,
  "decor--suite--code-block": SuiteCodeBlockController,
  "decor--suite--dropdown": SuiteDropdownController,
  "decor--suite--flash": SuiteFlashController,
  "decor--suite--forms--button-radio-group": SuiteFormsButtonRadioGroupController,
  "decor--suite--forms--checkbox": SuiteFormsCheckboxController,
  "decor--suite--forms--date-calendar": SuiteFormsDateCalendarController,
  "decor--suite--forms--expanding-checkbox-collection": SuiteFormsExpandingCheckboxCollectionController,
  "decor--suite--forms--file-upload": SuiteFormsFileUploadController,
  "decor--suite--forms--form": FormController,
  "decor--suite--forms--multi-image-upload": SuiteFormsMultiImageUploadController,
  "decor--suite--forms--number-field": SuiteFormsNumberFieldController,
  "decor--suite--forms--radio": SuiteFormsRadioController,
  "decor--suite--forms--searchable-multi-select": SuiteFormsSearchableMultiSelectController,
  "decor--suite--forms--searchable-select": SuiteFormsSearchableSelectController,
  "decor--suite--forms--select": SuiteFormsSelectController,
  "decor--suite--forms--switch": SuiteFormsSwitchController,
  "decor--suite--forms--text-area": SuiteFormsTextAreaController,
  "decor--suite--forms--text-field": SuiteFormsTextFieldController,
  "decor--suite--map": SuiteMapController,
  "decor--suite--modals--confirm": SuiteModalsConfirmController,
  "decor--suite--modals--confirm-modal": SuiteModalsConfirmModalController,
  "decor--suite--modals--confirm-template": SuiteModalsConfirmTemplateController,
  "decor--suite--modals--modal-close-button": SuiteModalsModalCloseButtonController,
  "decor--suite--modals--modal": SuiteModalsModalController,
  "decor--suite--modals--modal-open-button": SuiteModalsModalOpenButtonController,
  "decor--suite--modals--modal-trigger": SuiteModalsModalTriggerController,
  "decor--suite--notification-manager": SuiteNotificationManagerController,
  "decor--suite--polygon-editor": SuitePolygonEditorController,
  "decor--suite--progress": SuiteProgressController,
  "decor--suite--search-and-filter": SearchAndFilterController,
  "decor--suite--settings-list--row": RowController,
  "decor--suite--tables--bulk-actions-bar": SuiteTablesBulkActionsBarController,
  "decor--suite--tables--data-table-cell": DataTableCellController,
  "decor--suite--tables--data-table": DataTableController,
  "decor--suite--tables--tag-filter-bar": SuiteTablesTagFilterBarController,
  "decor--suite--tabs": SuiteTabsController,
  "decor--suite--tooltip": TooltipController,
};
