import { Controller } from "@hotwired/stimulus"

// Connects to data-controller="decor--daisy--forms--expanding-checkbox-collection"
//
// Toggles every descendant with the `.hideable` marker class between visible
// and hidden state, and flips the toggle button label between "Show more..."
// and "Show less...".
//
// The to-be-hidden rows must carry the prefixed Tailwind utility
// `decor:hidden` so the prefix-aware `.decor\:hidden { display: none }` rule
// generated by the gem's Tailwind v4 build hides them; the unprefixed
// `.hidden` class has no CSS effect under our prefix scheme.
export default class extends Controller {
  static targets = ["showMoreLink"]

  initialize() {
    this.showingMore = false
  }

  showMore() {
    this.element.querySelectorAll(".hideable").forEach((el) => {
      el.classList.toggle("decor:hidden")
    })
    this.showingMore = !this.showingMore
    if (this.hasShowMoreLinkTarget) {
      this.showMoreLinkTarget.textContent = this.showingMore ? "Show less..." : "Show more..."
    }
  }
}
